/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Crea y edita la landing, quiz y webhooks de un cliente
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Se genera automáticamente desde "name".
   */
  subdomain: string;
  active?: boolean | null;
  generalInfo: {
    companyName: string;
    legalName?: string | null;
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
    address?: string | null;
    /**
     * En formato horizontal
     */
    logo?: (number | null) | Media;
    privacyNoticeUrl?: string | null;
    termsUrl?: string | null;
  };
  /**
   * Si dejas el título vacío y no agregas bloques abajo, este tenant no tiene landing: la raíz del subdominio redirige directo al quiz.
   */
  landingHero?: {
    title?: string | null;
    subtitle?: string | null;
    image?: (number | null) | Media;
    ctaLabel?: string | null;
    ctaLink?: string | null;
  };
  landingBlocks?:
    | (
        | {
            heading?: string | null;
            body: string;
            ctaLabel?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            items?:
              | {
                  number: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            items?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'criteria';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            items?:
              | {
                  zone?: string | null;
                  name: string;
                  price?: string | null;
                  timeframe?: string | null;
                  description?: string | null;
                  badge?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projects';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  message: string;
                  name: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body?: string | null;
            ctaLabel?: string | null;
            ctaTarget?: ('quiz' | 'custom') | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaFinal';
          }
      )[]
    | null;
  /**
   * Configuración general de la barra de progreso / experiencia del quiz.
   */
  quizIntro?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    ctaLabel?: string | null;
  };
  /**
   * Cada paso se traduce 1:1 a un SurveyStep consumido por StepRenderer/formAtoms en el frontend del quiz.
   */
  quizSteps?:
    | {
        type:
          | 'text'
          | 'tel'
          | 'number'
          | 'textarea'
          | 'radio'
          | 'checkbox'
          | 'select'
          | 'state-mx'
          | 'opt-in'
          | 'checkpoint';
        /**
         * Nombre del campo en el formulario (react-hook-form). Debe ser único por paso.
         */
        name: string;
        /**
         * Soporta HTML simple (se renderiza con dangerouslySetInnerHTML).
         */
        title?: string | null;
        description?: string | null;
        placeholder?: string | null;
        /**
         * Si se define, el campo es obligatorio y este es el mensaje de error (inputOptions.required).
         */
        requiredMessage?: string | null;
        /**
         * Columnas del grid de opciones (Radio/Checkbox) o rows del textarea.
         */
        cols?: number | null;
        options?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Solo para pasos tipo "opt-in". Campos fijos: nombre y teléfono (obligatorios) y email (opcional).
         */
        optInFields?: {
          nombreTitle?: string | null;
          nombreRequiredMessage?: string | null;
          telefonoTitle?: string | null;
          telefonoRequiredMessage?: string | null;
          /**
           * El email nunca es obligatorio para el usuario.
           */
          emailTitle?: string | null;
        };
        /**
         * Avanza automáticamente al siguiente paso después de 5s (usado en checkpoints).
         */
        autoAdvance?: boolean | null;
        /**
         * Contenido a mostrar en un paso tipo "checkpoint".
         */
        checkpointContent?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        checkpointContentHTML?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Personaliza la página de gracias post-envío del quiz. Si se deja vacío, cae al copy genérico basado en generalInfo.
   */
  thankYouPage?: {
    title?: string | null;
    subtitle?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    contentHTML?: string | null;
  };
  /**
   * URL a la que se envía el lead cuando completa el opt-in inicial (antes de empezar el quiz).
   */
  optInWebhook?: string | null;
  /**
   * URL a la que se envían las respuestas completas del quiz (CRM, n8n, Zapier, etc).
   */
  quizWebhook: string;
  tracking?: {
    metaPixelId?: string | null;
    metaCapiToken?: string | null;
    googleTagId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  subdomain?: T;
  active?: T;
  generalInfo?:
    | T
    | {
        companyName?: T;
        legalName?: T;
        phone?: T;
        whatsapp?: T;
        email?: T;
        address?: T;
        logo?: T;
        privacyNoticeUrl?: T;
        termsUrl?: T;
      };
  landingHero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
        ctaLabel?: T;
        ctaLink?: T;
      };
  landingBlocks?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    number?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        criteria?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    zone?: T;
                    name?: T;
                    price?: T;
                    timeframe?: T;
                    description?: T;
                    badge?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    message?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaFinal?:
          | T
          | {
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaTarget?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  quizIntro?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ctaLabel?: T;
      };
  quizSteps?:
    | T
    | {
        type?: T;
        name?: T;
        title?: T;
        description?: T;
        placeholder?: T;
        requiredMessage?: T;
        cols?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        optInFields?:
          | T
          | {
              nombreTitle?: T;
              nombreRequiredMessage?: T;
              telefonoTitle?: T;
              telefonoRequiredMessage?: T;
              emailTitle?: T;
            };
        autoAdvance?: T;
        checkpointContent?: T;
        checkpointContentHTML?: T;
        id?: T;
      };
  thankYouPage?:
    | T
    | {
        title?: T;
        subtitle?: T;
        content?: T;
        contentHTML?: T;
      };
  optInWebhook?: T;
  quizWebhook?: T;
  tracking?:
    | T
    | {
        metaPixelId?: T;
        metaCapiToken?: T;
        googleTagId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}